/* Lógico estacionamento: */
CREATE DATABASE estacionamento;
USE estacionamento;

CREATE TABLE USUARIO (
    id_usuario VARCHAR(50) PRIMARY KEY,
    login VARCHAR(100),
    senha VARCHAR(100)
);

CREATE TABLE VEICULOS (
    id_veiculo VARCHAR(50) PRIMARY KEY,
    placa VARCHAR(100),
    cor VARCHAR(100),
    modelo VARCHAR(100),
    porte VARCHAR(20)
);

CREATE TABLE VAGA (
    id_vaga INT PRIMARY KEY,
    status_vaga VARCHAR(100)
);

CREATE TABLE REGISTRO_ESTACIONAMENTO (
    id_registro INT PRIMARY KEY,
    data_entrada DATE,
    data_saida DATE,
    hora_saida TIME,
    tempo_permanencia TIME,
    FK_VEICULOS_id_veiculo INT,
    FK_VAGA_id_vaga INT,
    FOREIGN KEY (FK_VEICULOS_id_veiculo) REFERENCES VEICULOS(id_veiculo),
    FOREIGN KEY (FK_VAGA_id_vaga) REFERENCES VAGA(id_vaga)
);

CREATE TABLE RELATORIO (
    id_relatorio INT PRIMARY KEY,
    tipo_relatorio VARCHAR(100),
    data_geracao DATE
);

CREATE TABLE BACKUP (
    id_backup INT PRIMARY KEY,
    data_backup DATE,
    horario_backup TIME
);

CREATE TABLE PAGAMENTO (
    id_pagamento INT PRIMARY KEY,
    tipo_pagamento VARCHAR(100),
    valor_pagamento FLOAT, -- alterei para FLOAT para consistência
    valor_total FLOAT,
    FK_REGISTRO_ESTACIONAMENTO_id_registro INT,
    FOREIGN KEY (FK_REGISTRO_ESTACIONAMENTO_id_registro) REFERENCES REGISTRO_ESTACIONAMENTO(id_registro)
);

CREATE TABLE GERENCIA (
    FK_USUARIO_id_usuario INT,
    FK_REGISTRO_ESTACIONAMENTO_id_registro INT,
    FOREIGN KEY (FK_USUARIO_id_usuario) REFERENCES USUARIO(id_usuario),
    FOREIGN KEY (FK_REGISTRO_ESTACIONAMENTO_id_registro) REFERENCES REGISTRO_ESTACIONAMENTO(id_registro)
);

CREATE TABLE GERA_relatorio (
    FK_REGISTRO_ESTACIONAMENTO_id_registro INT,
    FK_RELATORIO_id_relatorio INT,
    FOREIGN KEY (FK_REGISTRO_ESTACIONAMENTO_id_registro) REFERENCES REGISTRO_ESTACIONAMENTO(id_registro),
    FOREIGN KEY (FK_RELATORIO_id_relatorio) REFERENCES RELATORIO(id_relatorio)
);

CREATE TABLE GERA_backup (
    FK_RELATORIO_id_relatorio INT,
    FK_BACKUP_id_backup INT,
    FOREIGN KEY (FK_RELATORIO_id_relatorio) REFERENCES RELATORIO(id_relatorio),
    FOREIGN KEY (FK_BACKUP_id_backup) REFERENCES BACKUP(id_backup)
);

/* Relacionamentos adicionais */
ALTER TABLE GERENCIA ADD CONSTRAINT FK_GERENCIA_1
    FOREIGN KEY (FK_USUARIO_id_usuario) REFERENCES USUARIO(id_usuario)
    ON DELETE RESTRICT;

ALTER TABLE GERA_relatorio ADD CONSTRAINT FK_GERA_1
    FOREIGN KEY (FK_REGISTRO_ESTACIONAMENTO_id_registro)
    REFERENCES REGISTRO_ESTACIONAMENTO(id_registro)
    ON DELETE RESTRICT;

ALTER TABLE GERA_relatorio ADD CONSTRAINT FK_GERA_3
    FOREIGN KEY (FK_RELATORIO_id_relatorio)
    REFERENCES RELATORIO(id_relatorio)
    ON DELETE RESTRICT;

ALTER TABLE GERA_backup ADD CONSTRAINT FK_GERA_4
    FOREIGN KEY (FK_RELATORIO_id_relatorio)
    REFERENCES RELATORIO(id_relatorio)
    ON DELETE RESTRICT;

ALTER TABLE GERA_backup ADD CONSTRAINT FK_GERA_2
    FOREIGN KEY (FK_BACKUP_id_backup)
    REFERENCES BACKUP(id_backup)
    ON DELETE RESTRICT;

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_2
    FOREIGN KEY (FK_REGISTRO_ESTACIONAMENTO_id_registro)
    REFERENCES REGISTRO_ESTACIONAMENTO(id_registro);
